spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/Real_Time_Event_Ticketing_System

spring.datasource.username=root
spring.datasource.password=200363800727
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
